project_id = "zogjugtlsfmpxrwbdyfd"

[functions.ai-chat]
verify_jwt = true

[functions.generate-content]
verify_jwt = true

[functions.generate-poster]
verify_jwt = true

[functions.resume-builder]
verify_jwt = true

[functions.scrape-events]
verify_jwt = true

[functions.send-order-confirmation]
verify_jwt = false

[functions.send-certificate]
verify_jwt = false
