import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { QuizJoinCard } from "@/components/quiz/QuizJoinCard";
import { QuizLeaderboard } from "@/components/quiz/QuizLeaderboard";
import { useQuizRealtime } from "@/hooks/useQuizRealtime";
import { useQuizHost } from "@/hooks/useQuizHost";
import { Plus, Play, StopCircle, SkipForward, Trash2, Edit, Eye, Users, Loader2 } from "lucide-react";

type QuizStatus = "draft" | "waiting" | "active" | "question_active" | "question_ended" | "completed";

interface Quiz {
  id: string;
  title: string;
  description: string | null;
  status: QuizStatus;
  quiz_code: string;
  max_participants: number | null;
  current_question_idx: number;
  created_at: string;
}

interface Question {
  id: string;
  quiz_id: string;
  question_text: string;
  options: string[];
  correct_option_index: number;
  time_limit_seconds: number;
  points: number;
  order_index: number;
  image_url: string | null;
}

export function QuizManager() {
  const { toast } = useToast();
  const [quizzes, setQuizzes] = useState<Quiz[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [selectedQuiz, setSelectedQuiz] = useState<Quiz | null>(null);
  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false);
  const [isQuestionDialogOpen, setIsQuestionDialogOpen] = useState(false);
  const [editingQuestion, setEditingQuestion] = useState<Question | null>(null);

  // Form states
  const [newQuizTitle, setNewQuizTitle] = useState("");
  const [newQuizDescription, setNewQuizDescription] = useState("");
  const [maxParticipants, setMaxParticipants] = useState("100");

  // Question form states
  const [questionText, setQuestionText] = useState("");
  const [options, setOptions] = useState(["", "", "", ""]);
  const [correctOption, setCorrectOption] = useState("0");
  const [timeLimit, setTimeLimit] = useState("30");
  const [points, setPoints] = useState("10");

  // Realtime data for selected quiz
  const { quiz: realtimeQuiz, participants, participantCount } = useQuizRealtime(selectedQuiz?.id || null);
  const { questions, fetchQuestions, openLobby, startQuiz, endQuiz, showQuestion, endQuestion, nextQuestion, calculateFinalRanks, isUpdating } = useQuizHost(selectedQuiz?.id || null);

  useEffect(() => {
    fetchQuizzes();
  }, []);

  useEffect(() => {
    if (selectedQuiz) {
      fetchQuestions();
    }
  }, [selectedQuiz, fetchQuestions]);

  const fetchQuizzes = async () => {
    setIsLoading(true);
    try {
      const { data, error } = await supabase
        .from("quizzes")
        .select("*")
        .order("created_at", { ascending: false });

      if (error) throw error;
      setQuizzes(data as Quiz[]);
    } catch (err) {
      console.error("Failed to fetch quizzes:", err);
      toast({
        title: "Error",
        description: "Failed to load quizzes",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const createQuiz = async () => {
    if (!newQuizTitle.trim()) return;

    try {
      const { data: user } = await supabase.auth.getUser();
      if (!user.user) throw new Error("Not authenticated");

      const { data, error } = await supabase
        .from("quizzes")
        .insert({
          title: newQuizTitle.trim(),
          description: newQuizDescription.trim() || null,
          max_participants: parseInt(maxParticipants) || 100,
          created_by: user.user.id,
          quiz_code: "", // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (error) throw error;

      toast({ title: "Quiz created!", description: `Code: ${data.quiz_code}` });
      setIsCreateDialogOpen(false);
      setNewQuizTitle("");
      setNewQuizDescription("");
      setMaxParticipants("100");
      fetchQuizzes();
    } catch (err: unknown) {
      const errorMessage = err instanceof Error ? err.message : "Failed to create quiz";
      toast({ title: "Error", description: errorMessage, variant: "destructive" });
    }
  };

  const deleteQuiz = async (quizId: string) => {
    if (!confirm("Are you sure you want to delete this quiz?")) return;

    try {
      const { error } = await supabase.from("quizzes").delete().eq("id", quizId);
      if (error) throw error;

      toast({ title: "Quiz deleted" });
      if (selectedQuiz?.id === quizId) setSelectedQuiz(null);
      fetchQuizzes();
    } catch (err: unknown) {
      const errorMessage = err instanceof Error ? err.message : "Failed to delete quiz";
      toast({ title: "Error", description: errorMessage, variant: "destructive" });
    }
  };

  const saveQuestion = async () => {
    if (!selectedQuiz || !questionText.trim()) return;

    const validOptions = options.filter((o) => o.trim());
    if (validOptions.length < 2) {
      toast({ title: "Error", description: "At least 2 options are required", variant: "destructive" });
      return;
    }

    try {
      const questionData = {
        quiz_id: selectedQuiz.id,
        question_text: questionText.trim(),
        options: validOptions,
        correct_option_index: parseInt(correctOption),
        time_limit_seconds: parseInt(timeLimit) || 30,
        points: parseInt(points) || 10,
        order_index: editingQuestion?.order_index ?? questions.length,
      };

      if (editingQuestion) {
        const { error } = await supabase
          .from("quiz_questions")
          .update(questionData)
          .eq("id", editingQuestion.id);
        if (error) throw error;
        toast({ title: "Question updated" });
      } else {
        const { error } = await supabase.from("quiz_questions").insert(questionData);
        if (error) throw error;
        toast({ title: "Question added" });
      }

      setIsQuestionDialogOpen(false);
      resetQuestionForm();
      fetchQuestions();
    } catch (err: unknown) {
      const errorMessage = err instanceof Error ? err.message : "Failed to save question";
      toast({ title: "Error", description: errorMessage, variant: "destructive" });
    }
  };

  const deleteQuestion = async (questionId: string) => {
    if (!confirm("Delete this question?")) return;

    try {
      const { error } = await supabase.from("quiz_questions").delete().eq("id", questionId);
      if (error) throw error;
      toast({ title: "Question deleted" });
      fetchQuestions();
    } catch (err: unknown) {
      const errorMessage = err instanceof Error ? err.message : "Failed to delete question";
      toast({ title: "Error", description: errorMessage, variant: "destructive" });
    }
  };

  const resetQuestionForm = () => {
    setQuestionText("");
    setOptions(["", "", "", ""]);
    setCorrectOption("0");
    setTimeLimit("30");
    setPoints("10");
    setEditingQuestion(null);
  };

  const editQuestion = (question: Question) => {
    setEditingQuestion(question);
    setQuestionText(question.question_text);
    const opts = [...question.options];
    while (opts.length < 4) opts.push("");
    setOptions(opts);
    setCorrectOption(String(question.correct_option_index));
    setTimeLimit(String(question.time_limit_seconds));
    setPoints(String(question.points));
    setIsQuestionDialogOpen(true);
  };

  const handleEndQuiz = async () => {
    await calculateFinalRanks();
    await endQuiz();
  };

  const getStatusBadge = (status: QuizStatus) => {
    const variants: Record<QuizStatus, "default" | "secondary" | "destructive" | "outline"> = {
      draft: "secondary",
      waiting: "outline",
      active: "default",
      question_active: "default",
      question_ended: "default",
      completed: "destructive",
    };
    return <Badge variant={variants[status]}>{status}</Badge>;
  };

  const quizUrl = selectedQuiz ? `${window.location.origin}/quiz?code=${selectedQuiz.quiz_code}` : "";
  const currentStatus = realtimeQuiz?.status || selectedQuiz?.status;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold">Live Quiz Manager</h2>
          <p className="text-muted-foreground">Create and manage interactive quizzes</p>
        </div>
        <Dialog open={isCreateDialogOpen} onOpenChange={setIsCreateDialogOpen}>
          <DialogTrigger asChild>
            <Button className="gap-2">
              <Plus className="h-4 w-4" />
              New Quiz
            </Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Create New Quiz</DialogTitle>
              <DialogDescription>Set up a new interactive quiz session</DialogDescription>
            </DialogHeader>
            <div className="space-y-4 py-4">
              <div className="space-y-2">
                <Label>Title</Label>
                <Input
                  placeholder="Quiz title"
                  value={newQuizTitle}
                  onChange={(e) => setNewQuizTitle(e.target.value)}
                />
              </div>
              <div className="space-y-2">
                <Label>Description (optional)</Label>
                <Textarea
                  placeholder="Brief description"
                  value={newQuizDescription}
                  onChange={(e) => setNewQuizDescription(e.target.value)}
                />
              </div>
              <div className="space-y-2">
                <Label>Max Participants</Label>
                <Input
                  type="number"
                  value={maxParticipants}
                  onChange={(e) => setMaxParticipants(e.target.value)}
                />
              </div>
              <Button onClick={createQuiz} className="w-full">
                Create Quiz
              </Button>
            </div>
          </DialogContent>
        </Dialog>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Quiz List */}
        <Card className="lg:col-span-1">
          <CardHeader>
            <CardTitle>Your Quizzes</CardTitle>
          </CardHeader>
          <CardContent>
            {isLoading ? (
              <div className="flex justify-center py-8">
                <Loader2 className="h-6 w-6 animate-spin" />
              </div>
            ) : quizzes.length === 0 ? (
              <p className="text-center text-muted-foreground py-8">No quizzes yet</p>
            ) : (
              <div className="space-y-2">
                {quizzes.map((quiz) => (
                  <div
                    key={quiz.id}
                    onClick={() => setSelectedQuiz(quiz)}
                    className={`p-3 rounded-lg border cursor-pointer transition-all hover:border-primary ${
                      selectedQuiz?.id === quiz.id ? "border-primary bg-primary/5" : ""
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <span className="font-medium truncate">{quiz.title}</span>
                      {getStatusBadge(quiz.status)}
                    </div>
                    <div className="text-xs text-muted-foreground mt-1">
                      Code: <span className="font-mono">{quiz.quiz_code}</span>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>

        {/* Quiz Details */}
        {selectedQuiz ? (
          <Card className="lg:col-span-2">
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle>{selectedQuiz.title}</CardTitle>
                  <CardDescription>{selectedQuiz.description}</CardDescription>
                </div>
                <div className="flex items-center gap-2">
                  {getStatusBadge(currentStatus || selectedQuiz.status)}
                  <Button
                    variant="ghost"
                    size="icon"
                    onClick={() => deleteQuiz(selectedQuiz.id)}
                  >
                    <Trash2 className="h-4 w-4" />
                  </Button>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <Tabs defaultValue="questions">
                <TabsList className="mb-4">
                  <TabsTrigger value="questions">Questions</TabsTrigger>
                  <TabsTrigger value="control">Control Panel</TabsTrigger>
                  <TabsTrigger value="participants">
                    Participants ({participantCount})
                  </TabsTrigger>
                  <TabsTrigger value="share">Share</TabsTrigger>
                </TabsList>

                <TabsContent value="questions" className="space-y-4">
                  <Button
                    variant="outline"
                    className="gap-2"
                    onClick={() => {
                      resetQuestionForm();
                      setIsQuestionDialogOpen(true);
                    }}
                  >
                    <Plus className="h-4 w-4" />
                    Add Question
                  </Button>

                  {questions.length === 0 ? (
                    <p className="text-center text-muted-foreground py-8">
                      No questions yet. Add some to get started!
                    </p>
                  ) : (
                    <div className="space-y-2">
                      {questions.map((q, idx) => (
                        <div
                          key={q.id}
                          className="flex items-center gap-3 p-3 rounded-lg border bg-card"
                        >
                          <span className="w-8 h-8 rounded-full bg-primary/10 text-primary flex items-center justify-center font-medium">
                            {idx + 1}
                          </span>
                          <div className="flex-1 min-w-0">
                            <p className="font-medium truncate">{q.question_text}</p>
                            <p className="text-xs text-muted-foreground">
                              {q.time_limit_seconds}s · {q.points} pts · {(q.options as string[]).length} options
                            </p>
                          </div>
                          <Button variant="ghost" size="icon" onClick={() => editQuestion(q)}>
                            <Edit className="h-4 w-4" />
                          </Button>
                          <Button variant="ghost" size="icon" onClick={() => deleteQuestion(q.id)}>
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </div>
                      ))}
                    </div>
                  )}
                </TabsContent>

                <TabsContent value="control" className="space-y-4">
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                    {currentStatus === "draft" && (
                      <Button onClick={openLobby} disabled={isUpdating || questions.length === 0} className="gap-2">
                        <Eye className="h-4 w-4" />
                        Open Lobby
                      </Button>
                    )}
                    {currentStatus === "waiting" && (
                      <Button onClick={() => showQuestion(0)} disabled={isUpdating} className="gap-2">
                        <Play className="h-4 w-4" />
                        Start Quiz
                      </Button>
                    )}
                    {currentStatus === "question_active" && (
                      <Button onClick={endQuestion} disabled={isUpdating} variant="secondary" className="gap-2">
                        <StopCircle className="h-4 w-4" />
                        End Question
                      </Button>
                    )}
                    {currentStatus === "question_ended" && (
                      <>
                        {(realtimeQuiz?.current_question_idx || 0) < questions.length - 1 ? (
                          <Button onClick={nextQuestion} disabled={isUpdating} className="gap-2">
                            <SkipForward className="h-4 w-4" />
                            Next Question
                          </Button>
                        ) : (
                          <Button onClick={handleEndQuiz} disabled={isUpdating} variant="destructive" className="gap-2">
                            <StopCircle className="h-4 w-4" />
                            End Quiz
                          </Button>
                        )}
                      </>
                    )}
                  </div>

                  {currentStatus && currentStatus !== "draft" && currentStatus !== "completed" && (
                    <Card>
                      <CardContent className="pt-4">
                        <div className="flex items-center gap-4">
                          <div className="flex items-center gap-2">
                            <Users className="h-5 w-5 text-muted-foreground" />
                            <span className="text-2xl font-bold">{participantCount}</span>
                            <span className="text-muted-foreground">participants</span>
                          </div>
                          {(currentStatus === "question_active" || currentStatus === "question_ended") && (
                            <div className="text-muted-foreground">
                              Question {(realtimeQuiz?.current_question_idx || 0) + 1} of {questions.length}
                            </div>
                          )}
                        </div>
                      </CardContent>
                    </Card>
                  )}

                  {currentStatus === "completed" && (
                    <div className="text-center py-8">
                      <p className="text-lg font-medium text-green-600">Quiz completed!</p>
                      <p className="text-muted-foreground">View participants tab for final rankings</p>
                    </div>
                  )}
                </TabsContent>

                <TabsContent value="participants">
                  <QuizLeaderboard participants={participants} showTop={50} />
                </TabsContent>

                <TabsContent value="share">
                  <QuizJoinCard quizCode={selectedQuiz.quiz_code} quizUrl={quizUrl} mode="display" />
                </TabsContent>
              </Tabs>
            </CardContent>
          </Card>
        ) : (
          <Card className="lg:col-span-2 flex items-center justify-center min-h-[400px]">
            <p className="text-muted-foreground">Select a quiz to manage</p>
          </Card>
        )}
      </div>

      {/* Question Dialog */}
      <Dialog open={isQuestionDialogOpen} onOpenChange={setIsQuestionDialogOpen}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>{editingQuestion ? "Edit Question" : "Add Question"}</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label>Question</Label>
              <Textarea
                placeholder="Enter your question"
                value={questionText}
                onChange={(e) => setQuestionText(e.target.value)}
              />
            </div>

            <div className="space-y-2">
              <Label>Options</Label>
              {options.map((opt, idx) => (
                <div key={idx} className="flex items-center gap-2">
                  <span className="w-6 text-center text-muted-foreground">{idx + 1}</span>
                  <Input
                    placeholder={`Option ${idx + 1}`}
                    value={opt}
                    onChange={(e) => {
                      const newOpts = [...options];
                      newOpts[idx] = e.target.value;
                      setOptions(newOpts);
                    }}
                  />
                </div>
              ))}
            </div>

            <div className="grid grid-cols-3 gap-4">
              <div className="space-y-2">
                <Label>Correct Answer</Label>
                <Select value={correctOption} onValueChange={setCorrectOption}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {options.map((_, idx) => (
                      <SelectItem key={idx} value={String(idx)}>
                        Option {idx + 1}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label>Time Limit (seconds)</Label>
                <Input
                  type="number"
                  value={timeLimit}
                  onChange={(e) => setTimeLimit(e.target.value)}
                  min="5"
                  max="120"
                />
              </div>
              <div className="space-y-2">
                <Label>Points</Label>
                <Input
                  type="number"
                  value={points}
                  onChange={(e) => setPoints(e.target.value)}
                  min="1"
                  max="100"
                />
              </div>
            </div>

            <Button onClick={saveQuestion} className="w-full">
              {editingQuestion ? "Update Question" : "Add Question"}
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
